### ISSUE TITLE
Vmware Horizon Client 2306 8.10

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#791]
Iḿ trying to get the newest client installed.
The bundle installed seems to fail already, I do not see the files in the package folder installed.
The python install seems to work a little bit different than for older versions.

This I found in the logs.
2023-10-01 09:02:46,894] Error: Cannot load installer for component: vmware-horizon-file-association.
[2023-10-01 09:02:46,895] Top level exception handler
Traceback (most recent call last):

Anybody successfull with this or some hints?

build:

INSTALLING VMVIEW
VMVIEW is not installed, we need to setup binary file.
This only needs to be done once.

Continue? (Y/N)
y
	not a dynamic executable
Extracting VMware Installer...done.
**Installation was unsuccessful.**
Extracting VMware Installer...done.
Unable to load gtk: No module named gtk, falling back to console.
Component Name       Component Long Name                      Component Version   
==================== ======================================== ====================
cp: cannot stat './packages/vmview/var/log/vmware/*': No such file or directory
sed: can't read ./packages/vmview/bin/vmware-view: No such file or directory
rm: cannot remove './packages/vmview/lib/vmware/libudev.so.0': No such file or directory
vmview: Setup Complete

Adding Packages to Filetree

[vmware-installer-576801.log](https://github.com/Thinstation/thinstation/files/12776744/vmware-installer-576801.log)
[vmware-installer-576863.log](https://github.com/Thinstation/thinstation/files/12776745/vmware-installer-576863.log)
[install.strace.TXT](https://github.com/Thinstation/thinstation/files/12776746/install.strace.TXT)

**Comment by rohrbachger** [comment]
I found:
No module named configparser.
I installed both py2 and 3 version in the build, but probably this does not help in the chroot for the install.
How I can fix this?
I don`t need this vmware-horizon-file-association, but I did not found a way to disable he installation.
I`s not really a component.


    exec fileObj in mod.__dict__
  File "/tmp/tmpACz9d4/.installer/8.10.0/vmware-horizon-file-association.py", line 7, in <module>
    import configparser
ImportError: No module named configparser

**Comment by Doncuppjr** [comment]
Hmmmm, might need to create a port for that python module and then add it to the manifest of ports that are put into a chroot for the VMware install. Alternatively, could put in a routine to install python ports into the special chroot for installing VMware.


Sent from Yahoo Mail for iPhone


On Tuesday, October 3, 2023, 5:04 AM, rohrbachger ***@***.***> wrote:




I found:
No module named configparser.
I installed both py2 and 3 version in the build, but probably this does not help in the chroot for the install.
How I can fix this?
I dont need this vmware-horizon-file-association, but I did not found a way to disable he installation. Is not really a component.
exec fileObj in mod.__dict__

File "/tmp/tmpACz9d4/.installer/8.10.0/vmware-horizon-file-association.py", line 7, in 
import configparser
ImportError: No module named configparser

**Comment by rohrbachger** [comment]
I think I fixed it.
Was not that complicate , I switched to python3 , pip 3 and it works. I tested the connection to our horizon farm.

I will test more and will put all the things together for commit.
One part for commit its just the needed changes in the package vmview.

More difficult is the part to get the gcc port updated, the steps are already documented in the wiki.
Probably I  need some help for this.

**Comment by Doncuppjr** [comment]
I ran your wiki page through the GPT, and cleaned it up a little. Thank you for the contribution.

**Comment by rohrbachger** [comment]
Where did you put it? It is not anymore in the Wiki at the same place, and unfortunately I have no copy...

I would like to add some more documentation, to make it other people easier to use.
We are using iPXE and boot an 500MB image over the network environment. (http)
With 1GB connection it is fast, 100Mbit is more slow..
Classic Windows AD environment, Windows DHCP, but Linux is delivering the ISO to the pxe clients with apache
This works well over the last years. PXE with iPXE is really cool, we are starting also WIndows PE with this for windows client installations. 
I think TS, iPXE are a very interesting combination in a smaller Windows network.
But to figure this all out to work in combination  takes ages.
The Clients are Lenovo, Dell, no disk necessary, just setup for PXE boot and getting the boot information with 
iPXE and TS. We are using VMview,  but this does not matter.

**Comment by Doncuppjr** [comment]
Update a Port


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Update a Port

A framework for making thin and light Linux based images for x86 based machines and thinclients. - Thinstation/t...
 |

 |

 |




    On Sunday, October 8, 2023 at 02:34:40 AM MDT, rohrbachger ***@***.***> wrote:  
 
 


Where did you put it? It is not anymore in the Wiki at the same place, and unfortunately I have no copy...

I would like to add some more documentation, to make it other people easier to use.
We are using iPXE and boot an 500MB image over the network environment. (http)
With 1GB connection it is fast, 100Mbit is more slow..
Classic Windows AD environment, Windows DHCP, but Linux is delivering the ISO to the pxe clients with apache
This works well over the last years. PXE with iPXE is really cool, we are starting also WIndows PE with this for windows client installations.
I think TS, iPXE are a very interesting combination in a smaller Windows network.
But to figure this all out to work in combination takes ages.
The Clients are Lenovo, Dell, no disk necessary, just setup for PXE boot and getting the boot information with
iPXE and TS. We are using VMview, but this does not matter.

**Comment by Aleksa2022** [comment]
> I think I fixed it. Was not that complicate , I switched to python3 , pip 3 and it works. I tested the connection to our horizon farm.

Can I ask you to clarify a little:
1. How did you switch to python 3?
2. How are you doing with certificates? - I have implemented my certificates and vmview 8.2 is perfectly assembled and running, but when I try to install version 8.8.1+, my certificates stop working. I don't change anything from the previous working version with 8.2, but they don't work.
So far I have managed to achieve an image with working certificates and updated components - Xorg, firmware, kernel, etc., but with the vmview 8.2 client...

**Comment by rohrbachger** [comment]
Sure, I can help.
Last week I finished testing, and we are running now VMware-Horizon-Client-2306-8.10.0-21964631.x64.bundle on about 20 ThinStations. If that works, we will rollout to about 100. 

Python3, that part is simple. I`m, unfortunately not very familiar with git, I`m still fighting to get a pull request working.
In the build/package/build/install  you need to change some lines. I attached the file, I needed to rename from install to install.txt.

To get this new version, and also already the 8.9 a more actual version version of gcc is needed. I was able with Don's help to get the gcc12.2 working. This tooks really long time..
I will try this weekend, to get 2 pull requests, one for view package and another for gcc.
I attached the renamed package file fo gcc,

My repository for thinstation is rohrbachger, you can see already the change for the view client what I have done.
The gcc is a large package, I was not able to put it on git, still searching a way.
If you are a little bit familiar, this wiki page I did can help:https://github.com/Thinstation/thinstation/wiki/Update-a-Port

Certificates:
In my company we are using an official wildcard certificate for horizon view. We newer had issues, but of course with testing on old machines we had to correct date and time sometimes... We are using Horizon UAG gateways with the free Kemp Load balancers for remote workers, for internal use in most cases thinstation ( still 100 laptops with windows on top)
The package ca-bundle is needed. But if you have a very closed environment, without internet access ( I remember, we had some issues a while ago) the verification of the vmware certificates may fail. Probably this is the reason for your issues.
Iḿ in the good situation to manage also the firewall, so I think we made exceptions for the certificate verification.
No access in the moment, but if details are needed let me know.

You wrote you updated XORG and kernel. This knowledge Iḿ interested in. I want to update XORG and XFCE, this will a big ask for the next months.. We have for an very old application some issues with the resolution and scaling.






[Pkgfile.ts-ports-core-gcc.txt](https://github.com/Thinstation/thinstation/files/13060106/Pkgfile.ts-ports-core-gcc.txt)
[install.txt](https://github.com/Thinstation/thinstation/files/13060043/install.txt)

**Comment by Doncuppjr** [comment]
I kind of have a 6.3 binary set compiled and waiting in the wings. Bugs with power management though. Might get to it this winter.


Sent from Yahoo Mail for iPhone


On Saturday, October 21, 2023, 1:14 AM, rohrbachger ***@***.***> wrote:




Sure, I can help.
Last week I finished testing, and we are running now VMware-Horizon-Client-2306-8.10.0-21964631.x64.bundle on about 20 ThinStations. If that works, we will rollout to about 100.

Python3, that part is simple. Im, unfortunately not very familiar with git, Im still fighting to get a pull request working.
In the build/package/build/install you need to change some lines. I attached the file, I needed to rename from install to install.txt.

To get this new version, and also already the 8.9 a more actual version version of gcc is needed. I was able with Don's help to get the gcc12.2 working. This tooks really long time..
I will try this weekend, to get 2 pull requests, one for view package and another for gcc.
I attached the renamed package file fo gcc,

My repository for thinstation is rohrbachger, you can see already the change for the view client what I have done.
The gcc is a large package, I was not able to put it on git, still searching a way.
If you are a little bit familiar, this wiki page I did can help:https://github.com/Thinstation/thinstation/wiki/Update-a-Port

Certificates:
In my company we are using an official wildcard certificate for horizon view. We newer had issues, but of course with testing on old machines we had to correct date and time sometimes... We are using Horizon UAG gateways with the free Kemp Load balancers for remote workers, for internal use in most cases thinstation ( still 100 laptops with windows on top)
The package ca-bundle is needed. But if you have a very closed environment, without internet access ( I remember, we had some issues a while ago) the verification of the vmware certificates may fail. Probably this is the reason for your issues.
Iḿ in the good situation to manage also the firewall, so I think we made exceptions for the certificate verification.
No access in the moment, but if details are needed let me know.

You wrote you updated XORG and kernel. This knowledge Iḿ interested in. I want to update XORG and XFCE, this will a big ask for the next months.. We have for an very old application some issues with the resolution and scaling.

Pkgfile.ts-ports-core-gcc.txt
install.txt

**Comment by Aleksa2022** [comment]
> You wrote you updated XORG and kernel. This knowledge Iḿ interested in. I want to update XORG and XFCE, this will a big ask for the next months.. We have for an very old application some issues with the resolution and scaling.

I'm sorry I didn't answer for a long time - I was away.
Regarding Xorg, everything is simple: you need to update Xorg-server, then Xorg-xf86-video... I was updating:
xorg-rgb
xorg-server
xorg-sessreg
xorg-util-macros
xorg-xcb-util
xorg-xcb-util-image
xorg-xcb-util-renderutil
xorg-xclock
xorg-xdpyinfo
xorg-xdriinfo
xorg-xev
xorg-xf86-video-dummy
xorg-xf86-video-intel
xorg-xf86-video-vesa
xorg-xf86-video-vmware
xorg-xfce
xorg-xfsinfo
xorg-xgamma
xorg-xhost
xorg-xinit
xorg-xkill
xorg-xlsfonts
xorg-xmodmap
xorg-xorg proto
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xset
xorg-xsetroot
xorg-xtrans
xorg-xvinfo
xorg-xwininfo

The rest is optional. But it works fine for me.
Sometimes, if there are problems with monitors (occasionally occurs), an update can help:
xorg-libx11
xorg-x11perf

I won't say anything about xfce - I was updating IceWM. With him, too, there were no special problems like
binutils, firmware and kernel are updated normally to 5.15.133. When updating to 5.19 ... I had some problems that I did not disassemble, but remained in the 5.15 branch.

**Comment by Aleksa2022** [comment]
> I kind of have a 6.3 binary set compiled and waiting in the wings. Bugs with power management though. Might get to it this winter.

As an addition to the working version: I would like the kernel, glibc, gcc, horizon client, cmake, meson to be updated. Something didn't work out for me with Mason - there are many components that ask for a version older than it is (AppStream: Meson version 0.55.3, but the project requires >= 0.62), but after updating meson, problems begin with updating other packages.
I have updated a lot of ports. There are quite a few of them that have not been updated since 2014-2017, but new versions have recently been released for them.

**Comment by Thinstation** [comment]
Yeah meson is a total PITA.

**Comment by Doncuppjr** [comment]
I might be able to push a temp branch next week.


Sent from Yahoo Mail for iPhone


On Monday, October 30, 2023, 8:32 AM, Alesandro ***@***.***> wrote:





I kind of have a 6.3 binary set compiled and waiting in the wings. Bugs with power management though. Might get to it this winter.


As an addition to the working version: I would like the kernel, glibc, gcc, horizon client, cmake, meson to be updated. Something didn't work out for me with Mason - there are many components that ask for a version older than it is (AppStream: Meson version 0.55.3, but the project requires >= 0.62), but after updating meson, problems begin with updating other packages.
I have updated a lot of ports. There are quite a few of them that have not been updated since 2014-2017, but new versions have recently been released for them.
